version: '3'
services:
  app: &app_base
    build: "."
    stdin_open: true
    tty: true
    ports:
      - $HTTP_PORT:3000
    # 起動時に毎回bundle installする / Dockerfileで bundle installせずに起動時に行う
    command: /bin/sh -c "yarn install --check-files && bundle install && bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: $RAILS_ENV
      NODE_ENV: $RAILS_ENV
      # bundler に gem の install 場所を伝える
      BUNDLE_APP_CONFIG: ./.bundle
      API_DB_USER: pguser
      API_DB_PASS: pgpass
      API_DB_HOST: postgres
      API_DB_PORT: 5432
      REDIS_URL: redis://redis:6379
      ROLLBAR_ACCESS_TOKEN: $ROLLBAR_ACCESS_TOKEN
    volumes:
      - .:/var/www/app
      - bundle:/var/www/app/vendor/bundle
      - node-modules:/var/www/app/node_modules
      - packs:/var/www/app/public/packs
    depends_on:
      - postgres
      - redis
  webpack:
    <<: *app_base
    command: /bin/sh -c "yarn install --check-files && bundle install && bin/webpack-dev-server"
    environment:
      NODE_ENV: $RAILS_ENV
      RAILS_ENV: $RAILS_ENV
      BUNDLE_APP_CONFIG: ./.bundle
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"
    tty: true
    stdin_open: true

  postgres:
    stdin_open: true
    tty: true
    restart: always
    image: postgres:11.6
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      TZ: Asia/Tokyo
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:3.2.11
    environment:
      TZ: Asia/Tokyo
    ports:
      - $REDIS_PORT:6379
    command: redis-server --appendonly yes

volumes:
  pgsql-data:
  bundle:
  node-modules:
  packs:
